<?php

return [
	'title' => 'Terms & Condition',
	'content' => "<h3 class='text-warning mrg20T'>Kebijakan pribadi</h3>
<p>Chancery Investment Management LTD, selalu menghormati privasi pengguna. Saat Anda berselancar di situs Chancery Investment Management LTD, perusahaan akan mengumpulkan informasi tertentu sehingga perusahaan dapat mengidentifikasi Anda dari banyak pengguna. Pernyataan berikut untuk mengungkapkan kebijakan privasi situs Chancery Investment Management LTD terkait dengan membuktikan bahwa komitmen perusahaan terhadap perlindungan privasi.</p>
<p>Sebelum Anda mendaftar untuk layanan apa pun, perusahaan akan mengungkapkan kepada Anda syarat dan ketentuan tambahan yang berkaitan dengan pengumpulan dan penggunaan informasi pengguna. Di sini, Anda akan mengerti informasi pribadi apa yang dikumpulkan, dan bagaimana menggunakannya, kapan dan bagaimana cara menggunakannya, bagaimana perusahaan melindungi informasi Anda dan siapa yang berhak mengakses informasi pribadi tersebut dan bagaimana Anda dapat memperbaiki ketidakakuratan informasi, apa informasi akan dikumpulkan dan langkah-langkah kegiatan.</p>
<p>Chancery Investment Management LTD mengumpulkan informasi pengguna dengan dua cara: pengguna dengan akses langsung ke dan diperoleh dari log server situs web perusahaan. Informasi yang diberikan pengguna: saat Anda mengirimkan formulir pendaftaran, perusahaan mungkin mengharuskan Anda memberikan nama, email, dan informasi pribadi lainnya. Anda akan mengungkapkan informasi yang lebih akurat sehingga perusahaan dapat menyesuaikan diri dengan pengalaman layanan Chancery Investment Management LTD yang lebih baik.</p>

<h3 class='text-warning mrg20T'>Informasi log web</h3>
<p>Saat Anda mengunjungi situs web Internet, Anda akan mengungkapkan informasi tentang diri Anda, seperti alamat IP, bidang waktu dan referensi Anda (seperti memberikan halaman Web terkait Manajemen Investasi yang Berkurang). Sama seperti situs-situs lain, Chancery Investment Management LTD akan mengumpulkan informasi dasar seperti itu. Ingatlah bahwa setiap kali Anda secara sukarela mengungkapkan informasi pribadi, informasi dapat dikumpulkan dan digunakan oleh yang lain.</p>
<p>Meskipun Chancery Investment Management LTD mencoba melindungi privasi informasi pribadi Anda, namun Chancery Investment Management LTD tidak menjamin Anda bahwa keamanan informasi yang dikirimkan ke Chancery Investment Management LTD pasti akan aman dan Anda harus mengambil risiko sendiri. Selanjutnya, Anda adalah satu-satunya orang yang memiliki kewajiban kerahasiaan informasi akun dan kata sandi Anda.</p>

<h3 class='text-warning mrg20T'>Bagaimana dan kapan informasi akan digunakan</h3>
<p>Perusahaan sesuai dengan informasi yang berbeda untuk melakukan berbagai tujuan. Informasi yang diberikan pengguna: informasi ini akan digunakan untuk keperluan personalisasi dan verifikasi. Log Jaringan Server: jenis informasi ini membantu perusahaan mengidentifikasi area paling populer di situs perusahaan. Chancery Investment Management LTD juga mengumpulkan alamat IP pengunjung untuk keperluan administrasi sistem.</p>

<h3 class='text-warning mrg20T'>Perusahaan pihak ketiga dan cookies</h3>
<p>Perusahaan pihak ketiga, termasuk Google untuk menunjukkan iklan Chancery Investment Management LTD di internet. Perusahaan pihak ketiga yang termasuk Google akan menggunakan cookies untuk menentukan halaman dan konten koneksi Anda, dan untuk mengirimkan iklan yang relevan kepada Anda. Anda dapat masuk ke laman penyisihan iklan Google untuk tidak ikut menggunakan kuki Google.</p>
<p>Bagaimana perusahaan melindungi informasi Anda: privasi dan keamanan informasi pribadi Anda penting bagi perusahaan. Tanpa seizin Anda, Chancery Investment Management LTD tidak akan mengungkapkan informasi pribadi Anda kepada pihak ketiga manapun. Informasi seperti data pengguna yang diungkapkan oleh Chancery Investment Management LTD kepada calon mitra bisnis tidak akan berisi informasi pribadi pengguna. Namun, informasi yang dikirimkan di internet tidak bisa dijamin seratus persen aman.</p>
<p>Mengingat hal ini, walaupun Chancery Investment Management LTD berkomitmen tegas untuk menerapkan tindakan untuk melindungi privasi pengguna, namun Chancery Investment Management LTD tidak dapat memastikan keamanan produk, layanan dan informasi yang dikirimkan di situs web Chancery Investment Management LTD.</p>

<h3 class='text-warning mrg20T'>Siapa yang berhak mengakses informasi ini</h3>
<p>Kecuali disebutkan secara khusus, tanpa izin dari pengguna, Chancery Investment Management LTD tidak akan mengungkapkan informasi identitas pribadi kepada pihak ketiga. Menurut undang-undang, untuk melindungi Chancery Investment Management LTD dan hak hukum pengguna atau keamanan publik dan keuntungannya, Chancery Investment Management LTD akan mengungkapkan informasi pribadi Anda.</p>
<p>Chancery Investment Management LTD berhak untuk memodifikasi dan berhak memperbarui kebijakan privasi ini, namun perusahaan akan menerbitkan pembaruan dan / atau perubahan kebijakan privasi di internet.</p>
<p>Semua perubahan kebijakan privasi akan segera berlaku setelah pengumuman di Internet. Perusahaan mendorong Anda untuk mengunjungi situs web kebijakan privasi Chancery Investment Management LTD dari waktu ke waktu. Jika Anda terus menggunakan situs web Chancery Investment Management LTD atau menerima email dari perusahaan, yang juga berarti Anda setuju dengan semua dan semua kebijakan privasi yang dimodifikasi.</p>

<h3 class='text-warning mrg20T'>Syarat dan Ketentuan Layanan</h3>
<p>Situs web ini dimiliki dan dikelola oleh Chancery Investment Management LTD, Anda harus mematuhi semua persyaratan dan ketentuan layanan yang diberikan. Begitu Anda masuk ke situs Web ini, ini menunjukkan bahwa Anda telah membaca dan menyetujui semua persyaratan dan ketentuan. Jika Anda tidak menyetujui persyaratan dan ketentuan ini, Anda harus berhenti menggunakan situs web ini.</p>

<h3 class='text-warning mrg20T'>Penolakan</h3>
<p>Informasi yang diberikan di situs ini hanya untuk tujuan informasi, dan bukan merupakan nasihat hukum yang mencerminkan perusahaan atau pengacaranya atau kliennya. Informasi yang diberikan di situs ini hanya untuk informasi dasar, namun tidak mencerminkan perkembangan hukum, penilaian atau kesepakatan hukum terkini. Meski website kami akan berusaha memberikan informasi yang paling akurat dan mutakhir, namun tidak menjanjikan ketepatan, instantaneity dan kelengkapan informasi yang diberikan. Informasi di situs ini tidak dimaksudkan untuk menciptakan dan merupakan hubungan pengacara-klien. Anda tidak boleh tanpa undang-undang otorisasi Anda dan saran profesional hukum atau saran legal lainnya, untuk melakukan tindakan berdasarkan informasi di situs ini. Informasi di situs ini tidak boleh ditafsirkan sebagai komitmen atau indikator kinerja masa depan.</p>
<p>Meskipun Chancery Investment Management LTD tidak memiliki niat untuk beriklan di situs ini, namun Anda berada dalam yurisdiksi yang akan dipandang sebagai iklan. Mempekerjakan setiap perusahaan jasa profesional adalah keputusan penting, dan sebaiknya tidak hanya berdasarkan iklan. Sebelum Anda memutuskan, mintalah perusahaan untuk mengirimkan informasi dan pengalaman tertulis kepada perusahaan Anda secara gratis.</p>
<p>Meskipun Chancery Investment Management LTD telah mencoba mematuhi semua persyaratan hukum dan etika negara yang terdaftar perusahaan saat mengkompilasi situs web ini, namun Website ini mungkin gagal mematuhi semua persyaratan hukum dan etika di setiap negara, Chancery Investment Management LTD tidak melanjutkan nama siapapun melalui website ini.</p>
<p>Berbagai artikel dan halaman dari situs ini mungkin berisi tautan ke sumber lain di Internet. Tautan ini diberikan kepada Anda oleh perusahaan, dan membantu Anda mengidentifikasi dan menemukan sumber Internet lain yang mungkin menarik bagi Anda, namun tidak mengungkapkan atau menyiratkan Chancery Investment Management LTD, berafiliasi atau terkait, atau diberi kuasa hukum untuk menggunakan merek dagang apa pun di dalamnya. link, merek dagang terdaftar, logo, cap hukum atau cap, atau simbol hak cipta.</p>

<h3 class='text-warning mrg20T'>Tidak ada jaminan dan batasan pernyataan kewajiban</h3>
<p>Informasi adalah 'asli', tanpa komitmen apapun, namun tidak termasuk terbatas pada jaminan dapat diperjualbelikan, tujuan tertentu atau tidak adanya pelanggaran, baik tersurat maupun tersirat. Anda harus mengambil risiko menggunakan situs ini. Anda akan menganggap semua download dan / atau penggunaan Situs ini atau melalui file Situs Web, informasi, atau konten komunikasi lainnya atau materi lainnya (terbatas namun tidak termasuk perangkat lunak) menimbulkan tanggung jawab dan risiko kerugian. Terlepas dari situasi dan teori hukum apa pun, Chancery Investment Management LTD, situs web yang dibuat, membuat atau menyediakan konten dari pemasok atau pihak lain, tidak bertanggung jawab atas Anda atau orang lain untuk mengakses atau menggunakan situs ini dan menghasilkan keuntungan apa pun. atau kehilangan pendapatan, kehilangan bisnis atau kehilangan data, atau kerugian tidak langsung, khusus, tidak sengaja atau gabungan kerugian.</p>

<h3 class='text-warning mrg20T'>Pemberitahuan hak cipta dan merek dagang</h3>
<p>Anda dapat mendownload, menggunakan dan menyalin materi di situs ini untuk keperluan pribadi dan non-komersial, namun semua materi salinan Anda harus memenuhi pemberitahuan hak cipta, merek dagang, atau hak kepemilikan lainnya yang relevan. Kecuali diizinkan dalam paragraf, Anda tidak diberi hak untuk menggunakan materi hak cipta, merek dagang, paten, atau hak kekayaan intelektual lainnya. Semua hak dipegang oleh Chancery Investment Management LTD dan / atau pihak ketiga manapun. Anda mungkin tidak membuat kerangka halaman Web kami tanpa izin tertulis dari Chancery Investment Management LTD.</p>

<p>Persyaratan berikut berlaku untuk pelanggan yang memiliki urusan bisnis dengan Chancery Investment Management LTD:</p>

<ol>
<li>Hak atas kekayaan intelektual - Selama Chancery Investment Management LTD menyediakan layanan, pelanggan dengan ini yang memberi kuasa kepada Chancery Investment Management LTD secara gratis, global, tidak eksklusif hak dan lisensi. Chancery Investment Management LTD berhak menentukan, menggunakan, menyalin, memodifikasi, menggunakan, menunjukkan, dan mengirimkan semua informasi yang disampaikan atau diteruskan kepada Chancery Investment Management LTD oleh nasabah yang termasuk merek dagang, merek dagang, seni, logo , dengan hak cipta karya atau informasi atau materi milik lainnya (secara kolektif disebut sebagai 'kekayaan intelektual'), hanya untuk Chancery Investment Management LTD untuk menyediakan layanan bagi pelanggan. Pelanggan mewakili dan menjamin bahwa ia memiliki semua kepemilikan atas hak kekayaan intelektual, dan memiliki kekuatan untuk menggunakan kekayaan intelektual mereka seperti yang dijelaskan dalam artikel ini, dan pelanggan memiliki wewenang untuk memberi kuasa kepada Chancery Investment Management LTD untuk menggunakan kekayaan intelektual seperti yang dijelaskan di atas. Pelanggan yang melanggar bagian dari pernyataan dan jaminan yang timbul dari semua klaim, kerusakan, tuntutan, kewajiban, biaya dan biaya (termasuk biaya pengacara yang wajar) dan kompensasi kepada Chancery Investment Management LTD.</li>
<li>Jaminan Terbatas - Kecuali untuk jaminan, Chancery Investment Management LTD mengecualikan setiap dan semua yang lainnya yang tidak ditentukan seperti yang ditunjukkan atau tersirat termasuk dapat diperjualbelikan secara jelas, agar sesuai dengan tujuan tertentu. Tidak masalah pidato atau tindakan Chancery Investment Management LTD, tidak menjadi jaminan.</li>
<li>Batasan tanggung jawab - Layanan atau tidak tanggung jawab layanan (baik berdasarkan pelanggaran kontrak atau garansi, kelalaian atau teori tanggung jawab yang ketat) yang diberikan oleh Chancery Investment Management LTD terbatas pada kredit atau untuk membayar pelanggan sejumlah yang sama dengan harga beli dari layanan ini. Chancery Investment Management LTD tidak bertanggung jawab atas kerusakan konsekuensial dalam kondisi apapun.</li>
<li>Biaya dan biaya penegakan - Jika ada tuntutan hukum atau tuntutan bahwa antara pelanggan dan Chancery Investment Management LTD, pelanggan harus bertanggung jawab untuk membayar biaya untuk Chancery Investment Management LTD saat perusahaan menjalankan hak mereka, termasuk namun tidak terbatas untuk biaya yang wajar dan biaya pengacara. Jika Nasabah melanggar kewajiban apapun (termasuk namun tidak terbatas pada, pelanggan tidak dapat membayar biaya tersebut), pelanggan setuju untuk membayar Chancery Investment Management LTD, semua biaya pengacara yang wajar, biaya penagihan dan biaya yang termasuk biaya berikutnya setelah penghakiman. . Selain itu, pelanggan mengakui dan menyetujui bahwa Chancery Investment Management LTD tidak diharuskan membayar deposit saat mencari kompensasi yang adil.</li>
<li>Ganti Rugi - Untuk pelanggan sendiri dan karyawan, agen, orang implementasi, orang manajemen, ahli waris atau penerima hak (pelanggan) melanggar kewajiban apapun, termasuk namun tidak terbatas pada pelanggaran persyaratan dan ketentuan pengguna, atau karena tersinggung atau tersangka tersinggung terhadap entitas pemerintah manapun atau lembaga Konstitusi, Ordonansi, doktrin Ordonansi, atau untuk kelalaian atau tindakan sengaja atau tidak sengaja yang menyebabkan manajemen dan karyawan manajemen saat ini dan masa depan, direktur, karyawan, pemegang saham dan agen (oleh pihak klaim) menderita, menanggung, bertanggung jawab atau untuk membayar kerugian, klien setuju untuk mengganti kerugian, melindungi dan mendukung Pihak yang Dilindungi dari setiap dan semua pertanggungjawaban, denda, denda, penyitaan, tuntutan, klaim, tindakan, proses, kerugian, kerusakan, biaya dan biaya terkait (termasuk namun tidak terbatas pada semua biaya pertahanan, biaya rekonsiliasi, biaya pengacara yang wajar dan biaya lainnya untuk tindakan peradilan atau administratif).</li>
<li>Hubungi kami - Jika Anda memiliki keraguan atau pertanyaan tentang persyaratan dan ketentuan pengguna atau halaman kami, silakan kirim email kepada kami.</li>
</ol>

<p>Disusun oleh Chancery Investment Management LTD. Tim manajemen</p>

"
];
